# Generated by Django 5.0.4 on 2024-04-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_APP', '0002_product_location_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location_state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
