# Generated by Django 5.0.4 on 2024-04-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_APP', '0003_product_location_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='locationId',
        ),
        migrations.AddField(
            model_name='product',
            name='location_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
