# Generated by Django 5.0.4 on 2024-05-02 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_APP', '0004_rename_location_product_locationid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('locationid', models.OneToOneField(db_column='locationid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='IMS_APP.location')),
                ('quantity', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
    ]
