# Generated by Django 5.0.4 on 2024-05-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_APP', '0005_location_alter_product_options_inventory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
